### PR TITLE
Print Button for SO

### PR DESCRIPTION
**Pull request by OjasviAgarwal**
### Description
This functionality is required to give an option to the Security Officer in order to print the events for the day which can then be handed over to the Floor In-Charge.
Dependencies required:
@material-ui/core
react@16.3.0
react-dom@latest

Fixes # 31

### Type of Change:
**Delete irrelevant options.**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by rsarky** [comment]
@OjasviAgarwal Could you include a description of the PR and reference the specific issue.

**Comment by bhawesh96** [comment]
Also, squash your commits into one

**Comment by OjasviAgarwal** [comment]
> @OjasviAgarwal Could you include a description of the PR and reference the specific issue.

Done.

**Comment by OjasviAgarwal** [comment]
> 1. Synchronise your branch with upstream
> 2. Run `standard`. There are a lot of errors. Indentation issues too
> 3. UI is not mobile responsive. Even desktop UI is not upto the mark.
> 4. The image is clickable
> 5. You've simply copy pasted from the function above in `firebaseStorageService.js`. The endpoint is incorrect.
> 6. There's no functionality to select a date
> 7. The request body expects a date. That's totally ignored in your function.
> 
> Please test your code before sending a PR.

Sure, I ll look into all these changes.

**Comment by bhawesh96** [comment]
Will get it re-done in a new PR

**Pull request closed without merging**
